"""Remove local_id from table category

Revision ID: 080acb109513
Revises: d9323ff7cfe0
Create Date: 2025-09-17 20:21:46.753902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080acb109513'
down_revision: Union[str, Sequence[str], None] = 'd9323ff7cfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'local_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('local_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
