"""Add Image table

Revision ID: 6aae3f3f56bb
Revises: e2bc41fd6f1f
Create Date: 2025-09-19 20:41:42.839789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6aae3f3f56bb"
down_revision: Union[str, Sequence[str], None] = "e2bc41fd6f1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("local_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("recipe_local_id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_delete", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("idx_user_recipe_id"), table_name="image")
    op.create_index(
        "idx_user_recipe_id", "image", ["user_id", "recipe_local_id"], unique=False
    )
    op.drop_index(op.f("idx_user_updated"), table_name="image")
    op.create_index(
        "idx_user_updated", "image", ["user_id", "updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_updated", table_name="image")
    op.drop_index("idx_user_recipe_id", table_name="image")
    op.drop_table("image")
    # ### end Alembic commands ###
