"""Rename indexes

Revision ID: 6c2c05bb87a9
Revises: cf186b318bcf
Create Date: 2025-09-28 12:04:13.824052

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6c2c05bb87a9"
down_revision: Union[str, Sequence[str], None] = "cf186b318bcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_category_user_updated", "category", ["user_id", "updated_at"], unique=False
    )
    op.drop_index(op.f("idx_user_recipe_id"), table_name="image")
    op.drop_index(op.f("idx_user_updated"), table_name="image")
    op.create_index(
        "idx_image_user_recipe_id",
        "image",
        ["user_id", "recipe_local_id"],
        unique=False,
    )
    op.create_index(
        "idx_image_user_updated", "image", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "idx_ingredient_user_recipe_id",
        "ingredient",
        ["user_id", "recipe_local_id"],
        unique=False,
    )
    op.create_index(
        "idx_ingredient_user_updated",
        "ingredient",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_recipe_user_updated", "recipe", ["user_id", "updated_at"], unique=False
    )
    op.drop_index(op.f("idx_user_ingredient_id"), table_name="recipe_ingredient_link")
    op.create_index(
        "idx_link_user_ingredient_id",
        "recipe_ingredient_link",
        ["user_id", "ingredient_local_id"],
        unique=False,
    )
    op.create_index(
        "idx_link_user_recipe_id",
        "recipe_ingredient_link",
        ["user_id", "recipe_local_id"],
        unique=False,
    )
    op.create_index(
        "idx_link_user_updated",
        "recipe_ingredient_link",
        ["user_id", "updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_link_user_updated", table_name="recipe_ingredient_link")
    op.drop_index("idx_link_user_recipe_id", table_name="recipe_ingredient_link")
    op.drop_index("idx_link_user_ingredient_id", table_name="recipe_ingredient_link")
    op.create_index(
        op.f("idx_user_ingredient_id"),
        "recipe_ingredient_link",
        ["user_id", "ingredient_local_id"],
        unique=False,
    )
    op.drop_index("idx_recipe_user_updated", table_name="recipe")
    op.drop_index("idx_ingredient_user_updated", table_name="ingredient")
    op.drop_index("idx_ingredient_user_recipe_id", table_name="ingredient")
    op.drop_index("idx_image_user_updated", table_name="image")
    op.drop_index("idx_image_user_recipe_id", table_name="image")
    op.create_index(
        op.f("idx_user_updated"), "image", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        op.f("idx_user_recipe_id"),
        "image",
        ["user_id", "recipe_local_id"],
        unique=False,
    )
    op.drop_index("idx_category_user_updated", table_name="category")
    # ### end Alembic commands ###
