"""Add Images and indexes

Revision ID: 89492845fc5c
Revises: d4fe00206b46
Create Date: 2025-09-19 09:37:49.461909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89492845fc5c'
down_revision: Union[str, Sequence[str], None] = 'd4fe00206b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.create_index('idx_user_updated', 'category', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_category_local_id'), 'category', ['local_id'], unique=False)
    op.drop_index(op.f('ix_ingredient_title'), table_name='ingredient')
    op.create_index('idx_user_recipe_id', 'ingredient', ['user_id', 'recipe_local_id'], unique=False)
    op.drop_column('recipe', 'image')
    op.create_index('idx_user_ingredient_id', 'recipe_ingredient_link', ['user_id', 'ingredient_local_id'], unique=False)
    op.add_column('user', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity')
    op.drop_index('idx_user_updated', table_name='recipe_ingredient_link')
    op.drop_index('idx_user_recipe_id', table_name='recipe_ingredient_link')
    op.drop_index('idx_user_ingredient_id', table_name='recipe_ingredient_link')
    op.add_column('recipe', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_user_updated', table_name='recipe')
    op.drop_index('idx_user_updated', table_name='ingredient')
    op.drop_index('idx_user_recipe_id', table_name='ingredient')
    op.create_index(op.f('ix_ingredient_title'), 'ingredient', ['title'], unique=False)
    op.drop_index(op.f('ix_category_local_id'), table_name='category')
    op.drop_index('idx_user_updated', table_name='category')
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=False)
    # ### end Alembic commands ###
