"""Add index for public_id

Revision ID: cf186b318bcf
Revises: 6aae3f3f56bb
Create Date: 2025-09-20 11:33:57.678415

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cf186b318bcf"
down_revision: Union[str, Sequence[str], None] = "6aae3f3f56bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_image_public_id"), "image", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_public_id"), table_name="image")
    # ### end Alembic commands ###
