"""Add Recipe idx

Revision ID: e2bc41fd6f1f
Revises: 89492845fc5c
Create Date: 2025-09-19 10:04:46.422588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bc41fd6f1f'
down_revision: Union[str, Sequence[str], None] = '89492845fc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_updated'), table_name='recipe')
    op.create_index('idx_user_updated', 'recipe', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_updated', table_name='recipe')
    # ### end Alembic commands ###
