"""Change ingredient relations

Revision ID: e62f57974f9a
Revises: 6c2c05bb87a9
Create Date: 2025-10-02 10:58:29.081821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e62f57974f9a"
down_revision: Union[str, Sequence[str], None] = "6c2c05bb87a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_ingredient_user_recipe_id"), table_name="ingredient")
    op.drop_column("ingredient", "recipe_local_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredient",
        sa.Column("recipe_local_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("idx_ingredient_user_recipe_id"),
        "ingredient",
        ["user_id", "recipe_local_id"],
        unique=False,
    )
    # ### end Alembic commands ###
